### PR TITLE
Simplify signal_set API with result-based error handling

### LINKED ISSUE #28: signal_set API needs tidying
A lot of dual-error functions (error + exception). The error should probably be returned not taken as an outparam.

### PR DESCRIPTION
**Pull request by sgerbino**
- Replace throwing/error_code overload pairs with system::result<void>
  - Replace multiple signal constructors with variadic template
  - Add error checking for signal() calls when restoring SIG_DFL
  - Fix signal validation to allow signal 0

Resolves #28.

## Summary by CodeRabbit

* **New Features**
  * Added variadic constructor for signal sets enabling initialization with multiple signals.
  * Enhanced TLS context configuration for secure HTTPS connections.

* **Bug Fixes**
  * Improved error handling in signal operations across POSIX and Windows platforms.

* **Refactor**
  * Modernized signal API return types for explicit error reporting and better error propagation.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: example/https-client/https_client.cpp [hunk 1]
```diff
@@ -63,8 +63,14 @@ run_client(
     // Connect to the server (throws on error)
     (co_await s.connect(corosio::endpoint(addr, port))).value();
 
+    // Configure TLS context
+    corosio::tls::context ctx;
+    ctx.set_hostname(hostname);
+    ctx.set_default_verify_paths().value();
+    ctx.set_verify_mode(corosio::tls::verify_mode::peer).value();
```
Comment (vinniefalco) [inline example/https-client/https_client.cpp:70]: This is really cool

File: include/boost/corosio/signal_set.hpp [hunk 2]
```diff
@@ -104,61 +97,42 @@ class BOOST_COROSIO_DECL signal_set : public io_object
...
-
-        @throws boost::system::system_error Thrown on failure.
-    */
-    signal_set(
-        capy::execution_context& ctx,
-        int signal_number_1,
-        int signal_number_2,
-        int signal_number_3);
+        int signal,
+        Signals... signals)
```
Comment (vinniefalco) [inline include/boost/corosio/signal_set.hpp:130]: Why even keep this though? Do we like it?

File: src/corosio/src/detail/posix/signals.cpp [hunk 3]
```diff
@@ -318,7 +315,10 @@ remove_signal(
 
     // Restore default handler on last global unregistration
     if (state->registration_count[signal_number] == 1)
-        ::signal(signal_number, SIG_DFL);
+    {
+        if (::signal(signal_number, SIG_DFL) == SIG_ERR)
+            return make_error_code(system::errc::invalid_argument);
```
Comment (vinniefalco) [inline src/corosio/src/detail/posix/signals.cpp:320]: would this also work:
```
return system::errc::invalid_argument;
```

File: src/corosio/src/detail/posix/signals.cpp [hunk 4]
```diff
@@ -336,20 +336,25 @@ remove_signal(
...
+
     while (signal_registration* reg = impl.signals_)
     {
         int signal_number = reg->signal_number;
 
         if (state->registration_count[signal_number] == 1)
-            ::signal(signal_number, SIG_DFL);
+        {
+            if (::signal(signal_number, SIG_DFL) == SIG_ERR && !first_error)
+                first_error = make_error_code(system::errc::invalid_argument);
```
Comment (vinniefalco) [inline src/corosio/src/detail/posix/signals.cpp:356]: would this work
```
first_error = system::errc::invalid_argument;
```

**Review by vinniefalco — APPROVED** [review]
